spring:
  application:
    name: onboarding-flow
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/onboarding_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: simple

server:
  port: ${PORT:8080}

logging:
  level:
    com.zealthy: INFO
    org.springframework.web: WARN
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
