spring:
  application:
    name: onboarding-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/onboarding_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: simple

server:
  port: 8080

logging:
  level:
    com.zealthy: DEBUG
    org.springframework.web: DEBUG
