spring:
  application:
    name: onboarding-flow
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/onboarding_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${PORT:8080}

logging:
  level:
    com.zealthy: INFO
    org.springframework.web: WARN
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
